#2E-unaldo-users
version: '2'
services:
  users-db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: auth
      MYSQL_HOST: users-db
  users-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - 4000:4000
    depends_on:
      - 'users-db'
