# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16c7f8f212988814651905f0729a6dc74318c5fc9b16064aab1a48f763c3acebc27fd8b25135a1155744a1595e2e86914a1a522cff1c6ae6b4bf10c58e8a9956

test:
  secret_key_base: 407241533798c069edff89678fe5a17eebd240ebb9e519e053518ebc9150add9b6f2fdfa3e30c7a99879339158c0053e9d10b4cf10140f583562e22365cd29df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
